version: '3'
services:
  mysql:
    image: mysql:8.0.28
    platform: linux/x86_64
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql
    networks:
      - default
  app:
    image: node:16.14.0
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm run watch
    networks:
      - default
    depends_on:
      - mysql
networks:
  default:
volumes:
  mysqldata:
